# Generated by Django 4.2.11 on 2026-04-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1116_datadeletionrequest_hogql_predicate"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="last_calculation_realtime_cohort",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
