# Generated by Django 4.2.29 on 2026-04-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analytics", "0022_reviewqueue_reviewqueueitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmproviderkey",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "Openai"),
                    ("anthropic", "Anthropic"),
                    ("gemini", "Gemini"),
                    ("together_ai", "Together AI"),
                    ("openrouter", "Openrouter"),
                    ("fireworks", "Fireworks"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="llmmodelconfiguration",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "Openai"),
                    ("anthropic", "Anthropic"),
                    ("gemini", "Gemini"),
                    ("together_ai", "Together AI"),
                    ("openrouter", "Openrouter"),
                    ("fireworks", "Fireworks"),
                ],
                max_length=50,
            ),
        ),
    ]
